{
  "formatVersion": "1.1",
  "component": {
    "group": "study_asm",
    "module": "asm_plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "asm_plugin-1.0.5.jar",
          "url": "asm_plugin-1.0.5.jar",
          "size": 11568,
          "sha512": "ed45dab7a6bac778b3c678d2dac1902dd4c73e2cdbc9a447a1134e6f53f338cf364da1945c995d4c774c5d4f05615f98e2571e21c735267bb75d9d3921150612",
          "sha256": "30f41edfe1ab26c4be3e147a4c64f7082f55119ff6d1a3aa72a31cff3a5dd6a0",
          "sha1": "cb0cc889ce769b9bd6058acd7d6d7e963c364a2a",
          "md5": "0f7e07f4284c69b839a850949f4182a4"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "asm_plugin-1.0.5.jar",
          "url": "asm_plugin-1.0.5.jar",
          "size": 11568,
          "sha512": "ed45dab7a6bac778b3c678d2dac1902dd4c73e2cdbc9a447a1134e6f53f338cf364da1945c995d4c774c5d4f05615f98e2571e21c735267bb75d9d3921150612",
          "sha256": "30f41edfe1ab26c4be3e147a4c64f7082f55119ff6d1a3aa72a31cff3a5dd6a0",
          "sha1": "cb0cc889ce769b9bd6058acd7d6d7e963c364a2a",
          "md5": "0f7e07f4284c69b839a850949f4182a4"
        }
      ]
    }
  ]
}
