{
  "formatVersion": "1.1",
  "component": {
    "group": "study_asm",
    "module": "asm_plugin",
    "version": "unspecified",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.3.3"
    }
  },
  "variants": [
    {
      "name": "apiElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-api",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "asm_plugin-unspecified.jar",
          "url": "asm_plugin-unspecified.jar",
          "size": 11565,
          "sha512": "c9fe75722183e009093deb9c7ef39160d95cffa09261112aa0da5fe048c8585d2aceb3100ba73607bcdec4acf8c7881cf41c21fc5009a1c57ace34f64da74801",
          "sha256": "e6b8f4d19662d3dfb0f1214a6a470b86043ff3b9f8e3f524c5a1d1a4cc21cbef",
          "sha1": "a0bcd707a74702ea1e14e690296ba232953b25df",
          "md5": "bc8ae699671b3b8f8c8a36fff7fec59a"
        }
      ]
    },
    {
      "name": "runtimeElements",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.jvm.environment": "standard-jvm",
        "org.gradle.jvm.version": 8,
        "org.gradle.libraryelements": "jar",
        "org.gradle.usage": "java-runtime",
        "org.jetbrains.kotlin.platform.type": "jvm"
      },
      "dependencies": [
        {
          "group": "com.android.tools.build",
          "module": "gradle",
          "version": {
            "requires": "7.2.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm",
          "version": {
            "requires": "8.0.1"
          }
        },
        {
          "group": "org.ow2.asm",
          "module": "asm-commons",
          "version": {
            "requires": "9.4"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib-jdk8",
          "version": {
            "requires": "1.7.10"
          }
        }
      ],
      "files": [
        {
          "name": "asm_plugin-unspecified.jar",
          "url": "asm_plugin-unspecified.jar",
          "size": 11565,
          "sha512": "c9fe75722183e009093deb9c7ef39160d95cffa09261112aa0da5fe048c8585d2aceb3100ba73607bcdec4acf8c7881cf41c21fc5009a1c57ace34f64da74801",
          "sha256": "e6b8f4d19662d3dfb0f1214a6a470b86043ff3b9f8e3f524c5a1d1a4cc21cbef",
          "sha1": "a0bcd707a74702ea1e14e690296ba232953b25df",
          "md5": "bc8ae699671b3b8f8c8a36fff7fec59a"
        }
      ]
    }
  ]
}
